// projects/health/src/components/Register.vue
<template>
    <div class="modal" v-if="register || login">
        <div class="register-fields register" v-if="register">
            <span class="close"
			:onclick="closeModal"
			>
				x
			</span>
            <p class="register-title">Register</p>
            <input
                class="fields"
                type="text"
                placeholder="First Name"
                required
				v-model="fields.firstName"
            />
            <input
                class="fields"
                type="text"
                placeholder="Last Name"
                required
				v-model="fields.lastName"
            />
            <input
                class="fields"
                type="text"
                placeholder="email"
                required
				v-model="fields.email"
            />
            <input
                class="fields"
                type="password"
                placeholder="password"
                required
				v-model="fields.password"
            />
            <input
                class="fields"
                type="date"
                name="birth"
                required
				v-model="fields.birth" 
            />
            <div class="bottom">
				<p
					class="not-registred"
				>
					already registred ? <span
											class="reg"
											ref="log"
											:onclick="loginRegister"
										>
											login
										</span>
				</p>
                <button
                class="register-button"
                >
                    register
                </button>
            </div>
            <div class="error" v-if="error"> some incorrect entries </div>
        </div>
        <div class="validated" v-if="registrated">
            <span class="close">x</span>
            <h1 class="register-success">Registration Successfull</h1>
            <img class="v" src="../assets/v.png" alt="" />
            <p class="message">
                We've sent you an email to <span id="email">{ formData?.email }.</span><br />
                You need to confirm your account ...
            </p>
        </div>
		<div class="login" v-if="login">
			<span
				class="close"
				:onclick="closeModal"
			>
				x
			</span>
            <p class="register-title">LOGIN</p>
            <input
                class="fields"
                type="text"
                placeholder="email"
                required
				v-model="fields.firstName"
            />
            <input
                class="fields"
                type="text"
                placeholder="password"
                required
				v-model="fields.lastName"
            />
			<div class="bottom">
				<p
					class="not-registred"
				>
					not registred yet ? <span
											class="reg"
											ref="reg"
											:onclick="loginRegister"
										>
											register
										</span>
				</p>
                <button
                class="register-button"
                >
                    Login
                </button>
            </div>
			<div class="error" v-if="error">Bad Credentials</div>
		</div>
    </div>
</template>

<script>
export default {
	name: 'register',
	data(){
		return {
			fields: {
				firstName: '',
				lastName: '',
				email: '',
				password: '',
				birth: '',
			},
			login: false,
			register: true,
			error: false,
			registrated: false
		}
	},
	methods: {
		handleChange(){
			console.log(this.fields)
		},
		submit(){
			// do something here !!!
		},
		loginRegister(e){
			const target = e.target
			if (target === this.$refs.log){
				this.register = false
				this.login = true
			} else if (target === this.$refs.reg){
				this.register = true,
				this.login = false
			}
		},
		closeModal(){
			this.register = false
			this.login = false
		}
	}

}
</script>

<style>
	div.modal{
		position: relative;
		width: 100vw;
		height: 100vh;
	}

	.login,
	.register-fields{
		background-color: var(--black);
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		padding: 2rem;
		border-radius: .5rem;
		width: 40rem;
		text-align: center;
		display: flex;
		flex-direction: column;
		align-items: center;
	}

	.fields{
		border-radius: .5rem;
		width: 30rem;
		font-style: oblique;
		margin: .8rem;
		font-size: 2rem;
		padding: 1rem;
	}

	.register-title{
		padding: 1rem;
		color: var(--white);
		text-transform: uppercase;
		font-weight: bold;
		font-size: 2.5rem;
	}

	.register-button{
		cursor: pointer;
		border-radius: .5rem;
		color: var(--black);
		background-color: var(--white);
		margin: .5rem 1rem;
		font-size: 2.2rem;
		padding: .8rem;
	}

	.error{
		top: 0;
		left: 50%;
		transform: translate(-50%, -100%);
		position: absolute;
		text-align: center;
		color: var(--red);
		font-size: 2.5rem;
	}

	.validated{
		color: var(--white);
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		text-align: center;
		padding: 2.5rem;
		border-radius: 1rem;
		display: flex;
		justify-content: space-between;
		align-items: center;
		flex-direction: column;
		height: 25rem;
		background-color: var(--black);
		display: none;
	}

	.close{
		font-size: 2.5rem;
		cursor: pointer;
		color: var(--red);
		position: absolute;
		top: 0;
		right: 1.8rem;
	}

	.register-success{
		color: var(--green);
	}

	.v{
		width: 10rem;
		height: 10rem;
	}

	.message{
		font-size: 2.2rem;
	}

	#email{
		font-style: italic;
		font-weight: bold;
	}

	.login{

	}

	.not-registred{
		font-size: 2rem;
		color: var(--white);
	}

	.reg{
		cursor: pointer;
		font-size: 2.2rem;
		text-decoration: underline;
	}

	.reg:hover{
		color: var(--green);
	}
</style>

// javaScript/framework/reactJs/first-jwt/client/src/Register.jsx
import { useState } from "react";

const RegisterLogin = () => {
    const handleChange = (e)=>{
        formData[e.target.name] = e.target.value
        setFormData(formData)
    }

    const submit = (e)=>{
        e.preventDefault()
        fetch("/user/test",{
            method: "POST",
            headers: {
                "content-type" : "application/json",
                // "Access-Control-Allow-Origin" : "*",
                // "Access-Control-Allow-Credentials" : "true"
            },
            body: JSON.stringify(formData)
        }).then(res => res.json())
        .then(data => {
            console.log(data)
            data.status === 'ok' ? setIsValidated(true) : setError(true)})
    }

    const [formData, setFormData] = useState({})
    const [error, setError] = useState(false)
    const [isvalidated, setIsValidated] = useState(false)
    return ( 
        <form className="container">
            {error && !isvalidated && <div className="error"> some incorrect entries </div>}
            
            {!isvalidated &&
            <div className="register-fields register">
                <p className="title l">Register</p>
                <input
                    className="fields name"
                    type="text" name="name"
                    placeholder="name"
                    value={ formData?.name}
                    onChange={handleChange}
                    required
                />
                <input
                    className="fields surname"
                    type="text"
                    name="surname"
                    placeholder="surname"
                    value={ formData?.username}
                    onChange={handleChange}
                    required
                />
                <input
                    className="fields email"
                    type="text"
                    name="email"
                    placeholder="email"
                    value={ formData?.email}
                    onChange={handleChange}
                    required
                />
                <input
                    className="fields password"
                    type="password"
                    name="password"
                    placeholder="password"
                    value={ formData?.password}
                    onChange={handleChange}
                    required
                />
                <input
                    className="fields birth"
                    type="date"
                    name="birth"
                    value={ formData?.password}
                    onChange={handleChange}
                    required 
                />
                <div className="bottom">
                    <button
                    className="register-button"
                    onClick={ submit}
                    >
                        register
                    </button>
                </div>
            </div>
            }
            {isvalidated &&
                <div className="validated">
                    <h1 className="rs">Registration Successfull</h1>
                    <img className="v" src="v.png" alt="" />
                    <p className="message">
                        We've sent you an email to <span id="em">{ formData?.email }.</span><br />
                        You need to confirm your account ...
                    </p>
                </div>

            }
        </form>
    );
}
 
export default RegisterLogin;
